### ISSUE TITLE
Investigate voice assistant

### ISSUE THREAD

**Issue by janosimas** [janosimas/homeserver#20]
> eu tenho a suite voice assitant rodando na minha instância do home assistant e não foi necessariamente difícil fazer o setup não.
> Segue a parte do meu docker-compose pra isso:

```
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model base-int8 --language en
    volumes:
      - ./whisper:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      default:
      vlan:
        ipv4_address: <static-ip>

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice en_GB-alba-medium
    volumes:
      - ./piper:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      default:
      vlan:
        ipv4_address: <static-ip>

  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    command: --preload-model 'ok_nabu' --debug
    volumes:
      - ./openwakeword:/custom
      - ./openwakeword:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 10400:10400
    networks:
      default:
      vlan:
        ipv4_address: <static-ip>
```

> O catch é criar ip estáticos numa vlan pros seus containers se vc tá usando um satellite tipo o Atom Echo da M5 ou qualquer outro custom satellite,
